# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'install packages'

- script: |
    yarn test --reporter xunit --reporter-options output=test-results.xml
  displayName: 'run unit tests'
  
- script: |
    ls
  displayName: 'ls'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '**/test-results.xml'

